### ISSUE TITLE
Using SocialSample Example.  Crashes when putting in own callbackUrl

### ISSUE THREAD

**Issue by ghost** [YahooArchive/yos-social-objc#5]
I'm trying to work through the SocialSample example included in the download and everything works fine until I try putting in my own callbackUrl.  The application then crashes.  I'm having a heck of a time tracking down where the problem occurs.

**Comment by zonble** [comment]
I have the same problem. I consider the reason is an object is over-released. Please take a look at the line 64 of YOSRequestClient.m, rspError is already an autorelease object, we should not call autorelease again.

By the way, after fixing the crash, we are still unable to use the callbackURL in our session. The server response says 'oauth_problem=signature_invalid' and it does not return a request token.

**Comment by knowsudhanshu** [comment]
Sample Project opens up safari for login but never comes back to the application. I think the callback URL "oob" is not working and also README.markdown is missing the steps about setting URL scheme for iOS api. I stuck there, please help.

**Comment by michaelchum** [comment]
Fixed in the latest revamped SDK
